### ISSUE TITLE
Changing domain can result in an empty chart.

### ISSUE THREAD

**Issue by davidebbo** [davidbau/covid-19-chart#52] opened 2020-05-03 00:31 UTC
@bleroy reported going to https://covid19chart.org/#/?stat=7day&scale=linear&include=WA&top=0&series=deaths&start=3%2F1%2F20&ratio=&advanced=1 and getting a broken graph on a OnePlus 6T.

![bleroy](https://user-images.githubusercontent.com/556238/80895515-ab005780-8c9a-11ea-942f-05189540a243.jpg)

May need to get more details.

**Comment by davidebbo** [comment] 2020-05-03 00:34
This was a link from facebook. I noticed that facebook is inserting a fbclid query string param, which maybe is throwing things off. So actual link is: https://covid19chart.org/?fbclid=IwAR0NmXd2khm8LnPGw6EF2X50jLD4HbK0TDNZ2v2xkYU5FfY_k5IJUfBqXl0#/?stat=7day&scale=linear&include=WA&top=0&series=deaths&start=3%2F1%2F20&ratio=&advanced=1. Though that works fine on my Pixel.

**Comment by bleroy** [comment] 2020-05-03 05:27
The problem seems to be that you need to hit the small reset button to bring back the graph.

**Comment by davidebbo** [comment] 2020-05-03 17:18
It's odd. The fields in your image are not what they should be. Even the start date doesn't match the URL. And Domain should bs US and not WA, and the include filed should have WA. There must be a bug somewhere. Maybe @davidbau will have some thoughts.

**Comment by davidbau** [comment] 2020-05-04 00:35
How very strange.  I have not been able to reproduce the problem with any
of the links in this bug - do we have a link that we know can reproduce the
issue?

**Comment by bleroy** [comment] 2020-05-04 07:33
Firefox, follow the link, switch region to WA. Graph goes away. Works every time for me.

**Comment by davidebbo** [comment] 2020-05-04 15:46
Oh I see. Sorry, totally missed your comment on FB where you said you were switching the region to WA!

Indeed, this does repro, probably on all browsers. So at least we're not dealing with a browser dependent issue, which would be more painful.

I think there is a rather complex relationship between Domain, Include and Top, which can lead to puzzling behavior.

@davidbau, my take is that when the Domain changes, we should always reset Include/Select/Top. Any attempt to merge the current view with the new Domain seems problematic. WDYT?

**Comment by davidbau** [comment] 2020-05-04 16:54
@bleroy thanks for the repro.  @davidebbo yes that solution makes sense.  There is some current code that does some of that (without resetting top) protected by some complex "if", but without comments and I do not remember what the "if" is trying to accomplish.

**Comment by davidbau** [comment] 2020-05-04 17:10
Thought about it a little more and fixed in 62d09cf630bf494efa034e279d3fcfb9e97cb1a6, plus added some comments.

**Closed by davidbau** 2020-05-04 17:10 UTC

**Comment by davidebbo** [comment] 2020-05-04 17:37
Thanks, that fixes the primary issue here. I could argue that behavior still feels somewhat arbitrary in some cases (whether your select is exactly the new domain vs *contains* it among others), but maybe it's too minor to worry about.
